Wisata/Controllers/ObjekController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Wisata.Controllers
{
    public class ObjekController : Controller
    {
        //
        // GET: /Objek/
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                using (var db = new OcphDbContext())
                {
                    var result = this.GetModel();
                    return View(result);
                }

            }else
            {
                return RedirectToAction("NotHaveAccess", "ErrorHanler");
            }
           

        }

        //
        // GET: /Objek/Details/5
        public ActionResult Details(int id)
        {
            if (Request.IsAuthenticated)
            {
                using (var db = new OcphDbContext())
                {
                    var result = this.GetModel().Where(O => O.ObjekID == id).FirstOrDefault();
                    return View(result);
                }
            }
            else
            {
                return RedirectToAction("NotHaveAccess", "ErrorHanler");
            }

        }

        //
        // GET: /Objek/Create
        public ActionResult Create()
        {
            if (Request.IsAuthenticated)
            {
                ViewBag.Kecamatans = this.GetKecamatans();
                return View();
            }else
                return RedirectToAction("NotHaveAccess", "ErrorHanler");
        }

        //
        // POST: /Objek/Create
        [HttpPost]
        public ActionResult Create(DataAccess.Models.objek model)
        {
            if (Request.IsAuthenticated)
            {
                try
                {
                    using (var db = new OcphDbContext())
                    {
                        var res = db.objeks.Insert(model);
                    }

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }else
                return RedirectToAction("NotHaveAccess", "ErrorHanler");
        }

        //
        // GET: /Objek/Edit/5
        public ActionResult Edit(int id)
        {
            if (Request.IsAuthenticated)
            {
                using (var db = new OcphDbContext())
                {
                    var result = this.GetModel().Where(O => O.ObjekID == id).FirstOrDefault();
                    ViewBag.Kecamatans = this.GetKecamatans();
                    return View(result);
                }
            }else
                return RedirectToAction("NotHaveAccess", "ErrorHanler");
        }

        //
        // POST: /Objek/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, DataAccess.Models.objek model)
        {
            if (Request.IsAuthenticated)
            {
                try
                {
                    // TODO: Add update logic here
                    using (var db = new OcphDbContext())
                    {
                        db.objeks.Update(O => new { O.ObjekID, O.KecamatanID, O.Nama_Objek, O.Lintang, O.Bujur, O.Jenis, O.Description }, model, O => O.ObjekID == id);
                    }
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }else
                return RedirectToAction("NotHaveAccess", "ErrorHanler");
        }

        //
        // GET: /Objek/Delete/5
        public ActionResult Delete(int id)
        {
            if (Request.IsAuthenticated)
            {
                using (var db = new OcphDbContext())
                {
                    var result = this.GetModel().Where(O => O.ObjekID == id).FirstOrDefault();
                    ViewBag.Kecamatans = this.GetKecamatans();
                    return View(result);
                }
            }else
                return RedirectToAction("NotHaveAccess", "ErrorHanler");
        }

        //
        // POST: /Objek/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            if (Request.IsAuthenticated)
            {
                try
                {
                    // TODO: Add delete logic here
                    using (var db = new OcphDbContext())
                    {
                        db.objeks.Delete(O => O.ObjekID == id);
                    }
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }else
                return RedirectToAction("NotHaveAccess", "ErrorHanler");
        }

        public object GetKecamatans()
        {
            using (var db = new OcphDbContext())
            {
                var result = db.kecamatans.Select().ToList();
                return result;
            }
        }

        private List<DataAccess.Models.objek> GetModel()
        {
            using (var db = new OcphDbContext())
            {

                var result = from h in db.objeks.Select().AsEnumerable()
                             join k in db.kecamatans.Select().AsEnumerable() on h.KecamatanID equals k.Id_Kecamatan
                             select new DataAccess.Models.objek
                             {
                                 KecamatanID = h.KecamatanID,  KecamatanName= k.Nama_Kecamatan, Description=h.Description,
                                Bujur =h.Bujur, Jenis=h.Jenis, Lintang = h.Lintang, Nama_Objek=h.Nama_Objek,ObjekID=h.ObjekID
                             };
                return result.ToList();
            }
        }
    }
}

Wisata/Controllers/ProfilController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Wisata.Controllers
{
    public class ProfilController : Controller
    {
        //
        // GET: /Profil/
        public ActionResult Index()
        {
            return View();
        }



        public ActionResult VisiMisi()
        {
            return View();
        }


        public ActionResult Sejarah()
        {
            return View();
        }

        public ActionResult StrukturOrganisasi()
        {
            return View();
        }




	}
}

Wisata/Controllers/galeryController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Wisata.DataAccess.Models;

namespace Wisata.Controllers
{
    public class galeryController : Controller
    {
        //
        // GET: /galery/
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                using (var db = new OcphDbContext())
                {
                    var result = db.objeks.Select();
                    ViewBag.Objeks = result.ToList();
                    return View();
                }
            }else
            {
                return RedirectToAction("NotHaveAccess", "ErrorHanler");
            }
           


        }
        public ActionResult UploadPhoto(FileUpload upload,HttpPostedFileBase file)
        {
            bool isSuccess = true;
            using (var db = new OcphDbContext())
            {
                try
                {
                    MemoryStream target = new MemoryStream();
                    file.InputStream.CopyTo(target);
                    byte[] data1 = target.ToArray();

                    byte[] data = data1;//DataAccess.Models.ImageHelpers.CreateThumbnail(data1,1024);

                    upload.ApplicationFileType = file.ContentType;
                    upload.CategoryFile = FileUploadType.Image;
                    upload.DataFile = data;
                    upload.FileName = file.FileName;

                    var Inserted = db.Photos.Insert(upload);
                    ViewBag.IsSaved = false;
                    if (Inserted)
                    {
                         isSuccess = true;
                    }
                    else
                        isSuccess = false;
                }
                catch (Exception)
                {

                    isSuccess = false;
                }

                if (isSuccess)
                {
                    return Json(new { Message = file.FileName});
                }
                else
                {
                    return Json(new { Message = "Error in saving file" });
                }
              
            }
        }

        [HttpGet]
        public JsonResult GetPictures(int id)
        {
            using (var db = new OcphDbContext())
            {
                var result = from data in db.Photos.Where(O => O.ObjeckId == id)
                             select new { Id = data.Id, FileData = Convert.ToBase64String(ImageHelpers.CreateThumbnail(data.DataFile,300,300)) };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
        }

        //
        // GET: /Galery/Details/5
        public ActionResult Details(int id)
        {
            using (var db = new OcphDbContext())
            {
                return View();
            }

        }

        //
        // GET: /Galery/Create
        public ActionResult Create()
        {
            using (var db = new OcphDbContext())
            {
                var result = db.objeks.Select();
                ViewBag.Objeks = result.ToList();
                return View();
            }
        }

        //
        // POST: /Transportasi/Create
        [HttpPost]
        public ActionResult Create(FormCollection model)
        {
            try
            {
                using (var db = new OcphDbContext())
                {
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Galery/Edit/5
        public ActionResult Edit(int id)
        {
            using (var db = new OcphDbContext())
            {
                return View();
            }

        }

        //
        // POST: /Galery/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection form)
        {
            try
            {
                // TODO: Add update logic here
                using (var db = new OcphDbContext())
                {
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Galery/Delete/5
        public ActionResult Delete(int id)
        {
            using (var db = new OcphDbContext())
            {
                db.Photos.Delete(O => O.Id == id);
                return RedirectToAction("Index");
            }
        }

        //
        // POST: /Galery/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                using (var db = new OcphDbContext())
                {
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Wisata/Controllers/userController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Wisata.Controllers
{
    public class userController : Controller
    {
        
        //
        // GET: /user/
        public ActionResult Index()
        {
            if (Request.IsAuthenticated && new Users( User.Identity.Name).IsAdmin)
            {
                using (var db = new OcphDbContext())
                {
                    var result = db.users.Select().ToList();
                    return View(result);
                }

            }else
            {
                return RedirectToAction("NotHaveAccess", "ErrorHanler");
            }
        }

        //
        // GET: /F\User/Details/5
        public ActionResult Details(string id)
        {
            if (Request.IsAuthenticated)
            {
                using (var db = new OcphDbContext())
                {
                    var result = db.users.Where(O => O.Id_User == id).FirstOrDefault();
                    return View(result);
                }
            }else
                return RedirectToAction("NotHaveAccess", "ErrorHanler");
        }

        //
        // GET: /User/Create
        public ActionResult Create()
        {
            if (Request.IsAuthenticated)
            {
                return View();
            }else

                return RedirectToAction("NotHaveAccess", "ErrorHanler");
        }

        //
        // POST: /User/Create
        [HttpPost]
        public ActionResult Create(DataAccess.Models.user model)
        {
            if (Request.IsAuthenticated)
            {
                try
                {
                    using (var db = new OcphDbContext())
                    {
                        var res = db.users.Insert(model);
                    }

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }else

                return RedirectToAction("NotHaveAccess", "ErrorHanler");
        }

        //
        // GET: /User/Edit/5
        public ActionResult Edit(string id)
        {
            if (Request.IsAuthenticated)
            {
                using (var db = new OcphDbContext())
                {
                    var result = db.users.Where(O => O.Id_User == id).FirstOrDefault();
                    return View(result);
                }
            }else

                return RedirectToAction("NotHaveAccess", "ErrorHanler");
            
        }


        public ActionResult Change(string Id, int status)
        {
            using(var db = new OcphDbContext())
            {
                int s;
                if(status==0)
                     s=1;
                else
                     s=0;
                var res = db.users.Update(O => new { O.Status }, new DataAccess.Models.user { Status = s, Id_User = Id }, O => O.Id_User == Id);
            }
            return RedirectToAction("Index");
        }


        //
        // POST: /User/Edit/5
        [HttpPost]
        public ActionResult Edit(string id, DataAccess.Models.user model)
        {
            if (Request.IsAuthenticated)
            {
                try
                {
                    // TODO: Add update logic here
                    using (var db = new OcphDbContext())
                    {
                        db.users.Update(O => new { O.Id_User, O.User }, model, O => O.Id_User == id);
                    }
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }else

                return RedirectToAction("NotHaveAccess", "ErrorHanler");
            
        }

        //
        // GET: /User/Delete/5
        public ActionResult Delete(string id)
        {
            if (Request.IsAuthenticated)
            {
                using (var db = new OcphDbContext())
                {
                    var result = db.users.Where(O => O.Id_User == id).FirstOrDefault();
                    return View(result);
                }
            }else
                return RedirectToAction("NotHaveAccess", "ErrorHanler");
        }

        //
        // POST: /User/Delete/5
        [HttpPost]
        public ActionResult Delete(string id, FormCollection collection)
        {
            if (Request.IsAuthenticated)
            {
                try
                {
                    // TODO: Add delete logic here
                    using (var db = new OcphDbContext())
                    {
                        db.users.Delete(O => O.Id_User == id);
                    }
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }else
                return RedirectToAction("NotHaveAccess", "ErrorHanler");
        }
    }
}

Wisata/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DINAS KEBUDAYAAN &amp; PARIWISATA KOTA JAYAPURA</title>
    <link href="/Content/bootstrap.css" rel="stylesheet" />
    <link href="/Content/bootstrap-responsive.min.css" rel="stylesheet" />
    <link href="/fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="/Content/main.css" rel="stylesheet" />
    <link href="/Content/sl-slide.css" rel="stylesheet" />
    <link href="/Content/site.css" rel="stylesheet" />

    <script src="/Scripts/modernizr-2.6.2.js"></script>

</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Wisata", "Index", "Home", null, new { @class = "navbar-brand" })

            </div>

            <div class="navbar-collapse collapsed">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Profil</a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Sejarah", "Sejarah", "Profil")</li>
                            <li>@Html.ActionLink("VisiMisi", "VisiMisi", "Profil")</li>
                            <li>@Html.ActionLink("Struktur Organisasi", "StrukturOrganisasi", "Profil")</li>

                        </ul>
                    </li>

                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Admin", "Index", "Administrator")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>


    @RenderBody()
    <footer id="footer">
        <div class="container">
            <div class="row-fluid">
                <div class="span5 cp">
                    <p>&copy; @DateTime.Now.Year - DINAS KEBUDAYAAN &amp; PARIWISATA KOTA JAYAPURA</p>
                </div>
                <!--/Copyright-->
                <div class="span6">
                    <ul class="social pull-right">
                        <li><a href="#"><i class="icon-facebook"></i></a></li>
                        <li><a href="#"><i class="icon-twitter"></i></a></li>
                        <li><a href="#"><i class="icon-pinterest"></i></a></li>
                        <li><a href="#"><i class="icon-linkedin"></i></a></li>
                        <li><a href="#"><i class="icon-google-plus"></i></a></li>
                        <li><a href="#"><i class="icon-youtube"></i></a></li>
                        <li><a href="#"><i class="icon-tumblr"></i></a></li>
                        <li><a href="#"><i class="icon-dribbble"></i></a></li>
                        <li><a href="#"><i class="icon-rss"></i></a></li>
                        <li><a href="#"><i class="icon-github-alt"></i></a></li>
                        <li><a href="#"><i class="icon-instagram"></i></a></li>
                    </ul>
                </div>

                <!--/Goto Top-->
            </div>
        </div>
    </footer>
    <script src="/Scripts/jquery-1.10.2.js"></script>

    <script src="/Scripts/bootstrap.js"></script>
    <script src="/Scripts/main.js"></script>
    <script src="/Scripts/jquery.ba-cond.min.js"></script>
    <script src="/Scripts/jquery.slitslider.js"></script>
    <script src="/Scripts/respond.js"></script>


    @RenderSection("scripts", required: false)
</body>
</html>
<!-- SL Slider -->
<script type="text/javascript">
$(function() {
    var Page = (function() {

        var $navArrows = $( '#nav-arrows' ),
        slitslider = $( '#slider' ).slitslider( {
            autoplay : true
        } ),

        init = function() {
            initEvents();
        },
        initEvents = function() {
            $navArrows.children( ':last' ).on( 'click', function() {
                slitslider.next();
                return false;
            });

            $navArrows.children( ':first' ).on( 'click', function() {
                slitslider.previous();
                return false;
            });
        };

        return { init : init };

    })();

    Page.init();
});
</script>

Wisata/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DINAS KEBUDAYAAN &amp; PARIWISATA KOTA JAYAPURA</title>
    <link href="/Content/bootstrap.css" rel="stylesheet" />
    <link href="/Content/bootstrap-responsive.min.css" rel="stylesheet" />
    <link href="/fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="/Content/main.css" rel="stylesheet" />
    <link href="/Content/sl-slide.css" rel="stylesheet" />
    <link href="/Content/site.css" rel="stylesheet" />

    <script src="/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/Dashboar.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   
                </ul>
                @Html.Partial("_LoginPartial")
            </div>

        </div>

    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">

                <ul class="nav nav-sidebar">
                    <li class="active"><a href="#">Menu <span class="sr-only">(current)</span></a></li>
                    <li>@Html.ActionLink("Kecamatan", "Index", "Kecamatan")</li>
                    <li>@Html.ActionLink("Objek Wisata", "Index", "Objek")</li>
                    <li>@Html.ActionLink("Hotel","Index","Hotel")</li>
                    <li>@Html.ActionLink("Kuliner", "Index", "Kuliner")</li>
                    <li>@Html.ActionLink("Tempat Belanja", "Index", "Belanja")</li>
                    <li>@Html.ActionLink("Artikel","Index","Artikel")</li>
                    <li>@Html.ActionLink("Rumah Sakit","Index","rumah_sakit")</li>
                    <li>@Html.ActionLink("Travel","Index","travel")</li>
                    <li>@Html.ActionLink("Galery", "Index", "galery")</li>
                    <li>@Html.ActionLink("Pengunjung", "Index", "pengunjung")</li>
                    <li>@Html.ActionLink("Users","Index","user")</li>
                </ul>

            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

                <div class="table-responsive">
                    <div class="container body-content">

                        @RenderBody()
                        <hr />
                    </div>

                </div>
            </div>


            
            </div>
        </div>
    <script src="/Scripts/jquery-1.10.2.js"></script>

    <script src="/Scripts/bootstrap.js"></script>
    <script src="/Scripts/main.js"></script>
    <script src="/Scripts/jquery.ba-cond.min.js"></script>
    <script src="/Scripts/jquery.slitslider.js"></script>
    <script src="/Scripts/respond.js"></script>


 @RenderSection("scripts", required: false)
    
</body>

</html>